version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      MAINTAINER: 'Aryan Sinha'
      VENDOR: 'xiaomi'
      CODENAME: 'olivewood'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      #PB_OFFICIAL: 'true'
      CHANGELOG: |
        - Bump to 3.5.0
        - Update Prebuilts to v11.0.2.0 QCQINXM
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: org-global
